services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    env_file: ./.env/traefik.env
    restart: unless-stopped
  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: ./.env/wordpress.env
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud1.rule=Host(`heuu.duckdns.org`)"
      - "traefik.http.routers.cloud1.entrypoints=websecure"
      - "traefik.http.services.cloud1.loadbalancer.server.port=80"
      - "traefik.http.routers.cloud1.tls=true"
    restart: unless-stopped
  phpmyadmin:
     image: phpmyadmin
     container_name: phpmyadmin
     env_file: ./.env/phpmyadmin.env
     depends_on:
       - mysql
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.pma.rule=Host(`pma.heuu.duckdns.org`)"
       - "traefik.http.routers.pma.entrypoints=websecure"
       - "traefik.http.services.pma.loadbalancer.server.port=80"
       - "traefik.http.routers.pma.tls=true"
     restart: unless-stopped
  mysql:
     image: mysql:8.0
     container_name: mysql
     env_file: ./.env/mysql.env
     command: --skip-ssl
     volumes:
       - mysql:/var/lib/mysql
     healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
       interval: 5s
       timeout: 5s
       retries: 3
     restart: unless-stopped
  wordpress-cli:
    image: wordpress:cli
    depends_on:
      wordpress:
        condition: service_started
      mysql:
        condition: service_healthy
    env_file: ./.env/wordpress.env
    volumes:
      - wordpress:/var/www/html
    command:
      - sh
      - -c
      - |
        if ! wp core is-installed; then
          wp core install --url="$$WORDPRESS_URL" --title="Mon Blog" --admin_user="$$ADMIN_USER" --admin_password="$$ADMIN_PASSWORD" --admin_email="$$ADMIN_EMAIL" --locale="fr_FR" --skip-email
        fi

volumes:
  wordpress:
  mysql:
  traefik:
