- name: cloud-1
  hosts: AWS
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Create the keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/docker.asc

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /home/ubuntu/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy the docker-compose.yml file
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/app/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy the .env
      copy:
        src: ./.env
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start Containers
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/app
